# Generated by Django 5.0.6 on 2024-06-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок объявления')),
                ('id_announcement', models.IntegerField(verbose_name='id объявления')),
                ('author', models.CharField(max_length=100, verbose_name='Автор объявления')),
                ('count_views', models.IntegerField(verbose_name='Количество просмотров объявления')),
                ('position', models.IntegerField(verbose_name='Позиция объявления')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'db_table': 'announvements',
            },
        ),
    ]
